export const API_URL ="https://mariadbtiimi3.herokuapp.com/api/vaates/"
export const API_URL_VALMISTAJA_DEL ="https://mariadbtiimi3.herokuapp.com/api/valmistajas/"
export const API_URL_VAATTEET ="https://mariadbtiimi3.herokuapp.com/rest/vaatteet"
export const API_URL_VALMISTAJAT ="https://mariadbtiimi3.herokuapp.com/rest/valmistajat"
export const DB_URL ="https://mariadbtiimi3.herokuapp.com/"